window.MOTIF_DATA = {
  groups: [
    {
      id: "existence",
      label: "Existence and Change",
      short: "Existence",
      accent: "#2f7d68",
      summary: "The primitives that make a system observable, bounded, and able to change."
    },
    {
      id: "memory",
      label: "Memory and Persistence",
      short: "Memory",
      accent: "#436fb6",
      summary: "How systems retain, find, copy, and align information across time."
    },
    {
      id: "intelligence",
      label: "Intelligence and Learning",
      short: "Learning",
      accent: "#9a6a1f",
      summary: "The loops that let a system encode reality, anticipate, search, and improve."
    },
    {
      id: "scale",
      label: "Structure and Scale",
      short: "Scale",
      accent: "#7b5aa6",
      summary: "The grammar of parts, scopes, interfaces, and macro-behavior."
    },
    {
      id: "resources",
      label: "Resources and Allocation",
      short: "Resources",
      accent: "#b55345",
      summary: "The pressure created by limits, waiting, and allocation choices."
    },
    {
      id: "coordination",
      label: "Coordination and Governance",
      short: "Governance",
      accent: "#2d6f83",
      summary: "How separate agents exchange information, decide, converge, and bargain."
    }
  ],
  motifs: [
    {
      number: 1,
      slug: "state",
      name: "State",
      group: "existence",
      question: "What currently exists?",
      essence: "A snapshot of system configuration at a moment in time.",
      why: "Without state, there is nothing to change, protect, communicate, or reason about.",
      absence: "Behavior becomes unpredictable because the system cannot inspect, reproduce, or verify what happened.",
      domains: ["CPU registers", "database rows", "cell chemistry", "balance sheets", "belief states", "legal codes"],
      visual: "lattice"
    },
    {
      number: 2,
      slug: "transition",
      name: "Transition",
      group: "existence",
      question: "How does it change?",
      essence: "A rule mapping one state to another.",
      why: "Transitions are the atomic unit of change; without them, state is inert.",
      absence: "The system freezes in its initial configuration and cannot evolve, compute, or respond.",
      domains: ["CPU instructions", "chemical reactions", "trade executions", "policy actions", "decisions", "legislation"],
      visual: "flow"
    },
    {
      number: 3,
      slug: "invariant",
      name: "Invariant",
      group: "existence",
      question: "What must remain true after every change?",
      essence: "A constraint that must hold before and after every transition.",
      why: "Invariants define legal change and keep optimization from becoming exploitation.",
      absence: "Unconstrained transitions find loopholes, game objectives, and erode the system's character.",
      domains: ["type safety", "homeostasis", "accounting equations", "bylaws", "moral axioms", "human rights"],
      visual: "constraint"
    },
    {
      number: 4,
      slug: "identity",
      name: "Identity",
      group: "existence",
      question: "What makes each thing uniquely itself?",
      essence: "A stable reference that persists across state changes.",
      why: "Identity lets the system distinguish same content from same entity over time.",
      absence: "Duplicates accumulate, references merge incorrectly, and continuity becomes ambiguous.",
      domains: ["UUIDs", "primary keys", "DNA sequences", "tax IDs", "self-concept", "national identity"],
      visual: "fingerprint"
    },
    {
      number: 5,
      slug: "boundary",
      name: "Boundary",
      group: "existence",
      question: "What separates inside from outside?",
      essence: "A partition of the universe into system and environment.",
      why: "Boundary is the scope delimiter of reality: local state and local rules become parseable.",
      absence: "Everything leaks into everything; isolation, protection, modularity, and self-definition fail.",
      domains: ["firewalls", "containers", "cell membranes", "legal entities", "personal space", "sovereignty"],
      visual: "membrane",
      callout: "Boundary is the parenthesis of reality."
    },
    {
      number: 6,
      slug: "terminal-state",
      name: "Terminal State",
      group: "existence",
      question: "When is it done?",
      essence: "A state from which no further transitions are needed or possible.",
      why: "Terminal states turn open-ended processes into bounded ones.",
      absence: "Systems run forever, drift indefinitely, or exhaust resources because there is no definition of done.",
      domains: ["HALT states", "fixpoints", "apoptosis", "settlement", "project completion", "treaty signing"],
      visual: "terminal"
    },
    {
      number: 7,
      slug: "decay",
      name: "Decay",
      group: "existence",
      question: "What degrades without maintenance?",
      essence: "The tendency of systems toward disorder without directed effort.",
      why: "Decay is what makes every other motif require renewal, repair, and maintenance.",
      absence: "Ignoring decay accumulates invisible structural debt until failure becomes sudden and expensive.",
      domains: ["bit rot", "clock drift", "aging", "depreciation", "culture erosion", "institutional rot"],
      visual: "entropy"
    },
    {
      number: 8,
      slug: "storage",
      name: "Storage",
      group: "memory",
      question: "Where does information persist?",
      essence: "A bounded region where state survives across time.",
      why: "Storage converts ephemeral information into durable memory and accumulated knowledge.",
      absence: "Every transition starts from scratch; the system has no usable history.",
      domains: ["disk", "databases", "DNA", "ledgers", "wikis", "archives"],
      visual: "archive"
    },
    {
      number: 9,
      slug: "addressing",
      name: "Addressing",
      group: "memory",
      question: "How do you find what you need?",
      essence: "A systematic way to locate a specific entity.",
      why: "Addressing turns identity into retrieval.",
      absence: "Knowledge may exist, but it cannot be found when needed.",
      domains: ["URLs", "file paths", "DNS", "gene loci", "ticker symbols", "GPS coordinates"],
      visual: "locator"
    },
    {
      number: 10,
      slug: "replication",
      name: "Replication",
      group: "memory",
      question: "Can multiple copies exist?",
      essence: "Creating copies of stored information across locations.",
      why: "Replication buys availability and resilience while creating consistency risk.",
      absence: "A single copy becomes a bottleneck and a point of failure.",
      domains: ["caches", "CDNs", "RAID", "cell division", "franchises", "cultural diffusion"],
      visual: "copies"
    },
    {
      number: 11,
      slug: "synchronization",
      name: "Synchronization",
      group: "memory",
      question: "How do copies stay consistent?",
      essence: "Ensuring that replicated copies converge to a consistent state.",
      why: "Synchronization detects divergence and aligns copies under a definition of consistency.",
      absence: "Different parts of the system believe different things and conflicts spread silently.",
      domains: ["cache coherence", "Raft", "CRDTs", "circadian rhythms", "audits", "status reports"],
      visual: "sync"
    },
    {
      number: 12,
      slug: "representation",
      name: "Representation",
      group: "intelligence",
      question: "How is reality encoded?",
      essence: "A mapping from external reality to internal state.",
      why: "The quality of representation sets the ceiling on what a system can reason about.",
      absence: "The system cannot reason beyond immediate input or express what matters.",
      domains: ["embeddings", "knowledge graphs", "DNA codons", "price signals", "dashboards", "maps"],
      visual: "encoder"
    },
    {
      number: 13,
      slug: "feedback",
      name: "Feedback",
      group: "intelligence",
      question: "How does the outcome of a transition influence future transitions?",
      essence: "Routing output information back as input.",
      why: "Feedback converts a static system into a learning system.",
      absence: "Errors persist indefinitely because outcomes do not alter future behavior.",
      domains: ["test results", "monitoring", "natural selection", "profit and loss", "retrospectives", "elections"],
      visual: "loop"
    },
    {
      number: 14,
      slug: "prediction",
      name: "Prediction",
      group: "intelligence",
      question: "What happens next?",
      essence: "An internal model generating expected future states.",
      why: "Prediction separates reactive systems from proactive ones.",
      absence: "The system is always behind, always surprised, and always adapting late.",
      domains: ["branch prediction", "LLM next-token prediction", "immune memory", "futures markets", "planning", "intelligence agencies"],
      visual: "forecast",
      composition: ["representation", "feedback"]
    },
    {
      number: 15,
      slug: "search",
      name: "Search",
      group: "intelligence",
      question: "How do you find a valid path?",
      essence: "Systematic exploration of a possibility space under constraints.",
      why: "Search is what a system does when it does not already know the answer.",
      absence: "The system cannot discover alternatives or escape brute-force trial.",
      domains: ["A*", "SAT solvers", "evolution", "foraging", "R&D pipelines", "legal discovery"],
      visual: "maze"
    },
    {
      number: 16,
      slug: "model",
      name: "Model",
      group: "intelligence",
      question: "What internal simulation exists?",
      essence: "A bounded internal simulation of external reality.",
      why: "Models enable counterfactual reasoning: what could happen if conditions changed.",
      absence: "The system cannot plan, test hypotheticals, or reason beyond what is.",
      domains: ["simulators", "digital twins", "financial models", "mental simulation", "war games", "scenario plans"],
      visual: "simulation",
      composition: ["representation", "prediction", "boundary"]
    },
    {
      number: 17,
      slug: "compression",
      name: "Compression",
      group: "intelligence",
      question: "How can less describe more?",
      essence: "Encoding maximum information in minimum space.",
      why: "Compression is the ability to find structure beneath surface detail.",
      absence: "The system drowns in data without generalization or understanding.",
      domains: ["codecs", "summaries", "theories", "proverbs", "constitutions", "schemas"],
      visual: "fold",
      composition: ["representation", "scarcity"]
    },
    {
      number: 18,
      slug: "optimization",
      name: "Optimization",
      group: "intelligence",
      question: "What should improve?",
      essence: "Directed improvement under constraints.",
      why: "Optimization gives purpose to prediction, search, and feedback.",
      absence: "Effort has no preference structure and cannot distinguish better from merely different.",
      domains: ["gradient descent", "routing", "selection pressure", "portfolio strategy", "process improvement", "policy design"],
      visual: "gradient",
      composition: ["prediction", "search", "scarcity"]
    },
    {
      number: 19,
      slug: "explore-exploit",
      name: "Explore / Exploit",
      group: "intelligence",
      question: "Learn or use?",
      essence: "The tradeoff between acquiring new information and acting on existing knowledge.",
      why: "Intelligent systems must balance novelty against reliable returns.",
      absence: "Too much exploration wastes resources; too much exploitation creates brittleness and local optima.",
      domains: ["bandit algorithms", "R&D portfolios", "foraging", "career choices", "investment strategy", "scientific agendas"],
      visual: "split"
    },
    {
      number: 20,
      slug: "self-reference",
      name: "Self-Reference",
      group: "intelligence",
      question: "When does a system reference itself?",
      essence: "A system containing or operating on a representation of itself.",
      why: "Self-reference enables reflection, self-improvement, and meta-reasoning.",
      absence: "The system cannot inspect or deliberately alter its own structure.",
      domains: ["self-compilers", "reflection APIs", "autopoiesis", "meta-markets", "metacognition", "constitutional amendment"],
      visual: "recursion"
    },
    {
      number: 21,
      slug: "composition",
      name: "Composition",
      group: "scale",
      question: "How do pieces combine?",
      essence: "Constructing complex wholes from simpler elements.",
      why: "Composition is the foundation of all larger structure.",
      absence: "The universe remains a flat field of isolated atoms with no organization.",
      domains: ["functions", "microservices", "org units", "molecules", "legal clauses", "institutions"],
      visual: "assembly"
    },
    {
      number: 22,
      slug: "hierarchy",
      name: "Hierarchy",
      group: "scale",
      question: "How do small things form larger things under direction?",
      essence: "Composition with authority.",
      why: "Hierarchy coordinates complexity without requiring every element to talk to every other.",
      absence: "Coordination costs explode as every part must negotiate with every part.",
      domains: ["call stacks", "org charts", "nervous systems", "military command", "taxonomies", "federations"],
      visual: "tree",
      composition: ["composition", "authority"]
    },
    {
      number: 23,
      slug: "modularity",
      name: "Modularity",
      group: "scale",
      question: "What can change independently?",
      essence: "Bounded parts with well-defined interfaces.",
      why: "Modularity makes complex systems maintainable.",
      absence: "Changes cascade unpredictably because everything is coupled to everything else.",
      domains: ["packages", "APIs", "org teams", "organs", "product lines", "federalism"],
      visual: "modules",
      composition: ["boundary", "composition"]
    },
    {
      number: 24,
      slug: "abstraction",
      name: "Abstraction",
      group: "scale",
      question: "What can be hidden?",
      essence: "Hiding internal complexity behind a simpler interface.",
      why: "Abstraction lets a system reason at the level that matters for the current purpose.",
      absence: "Every decision must carry all details, making comprehension and change expensive.",
      domains: ["interfaces", "models", "roles", "laws", "maps", "categories"],
      visual: "veil",
      composition: ["boundary", "representation"]
    },
    {
      number: 25,
      slug: "emergence",
      name: "Emergence",
      group: "scale",
      question: "How do micro-behaviors produce macro-properties?",
      essence: "Properties that exist at the whole level but not the component level.",
      why: "Emergence explains why reduction alone cannot predict every system behavior.",
      absence: "The system misses macro-patterns that arise from local interactions.",
      domains: ["traffic waves", "consciousness", "market crashes", "culture", "flocking", "public opinion"],
      visual: "swarm",
      composition: ["composition", "feedback"]
    },
    {
      number: 26,
      slug: "scarcity",
      name: "Scarcity",
      group: "resources",
      question: "What is limited?",
      essence: "The condition that demand exceeds supply.",
      why: "Scarcity forces choice, and choice makes intelligence necessary.",
      absence: "With no limits, there is no need for optimization, scheduling, negotiation, or prioritization.",
      domains: ["CPU time", "capital", "attention", "energy", "housing", "political will"],
      visual: "reservoir"
    },
    {
      number: 27,
      slug: "queue",
      name: "Queue",
      group: "resources",
      question: "Who waits?",
      essence: "An ordered collection of pending demands.",
      why: "Queues make the hidden cost of scarcity visible.",
      absence: "Unmet demand remains invisible and contention looks like random friction.",
      domains: ["job queues", "support tickets", "waiting rooms", "backlogs", "supply chains", "visa lines"],
      visual: "queue",
      composition: ["scarcity", "composition"]
    },
    {
      number: 28,
      slug: "scheduling",
      name: "Scheduling",
      group: "resources",
      question: "Who gets resources next?",
      essence: "A decision procedure for allocating scarce resources over time.",
      why: "A schedule encodes the system's values: fairness, urgency, priority, or efficiency.",
      absence: "Competing demands collide without a temporal policy for resolution.",
      domains: ["CPU schedulers", "calendars", "triage", "dispatch", "court dockets", "legislative agendas"],
      visual: "timeline",
      composition: ["queue", "authority"]
    },
    {
      number: 29,
      slug: "communication",
      name: "Communication",
      group: "coordination",
      question: "How does information move?",
      essence: "The transfer of information across a boundary.",
      why: "Communication is the only mechanism by which separate systems coordinate.",
      absence: "Bounded parts cannot align, warn, negotiate, or share state.",
      domains: ["messages", "APIs", "hormones", "prices", "meetings", "diplomacy"],
      visual: "signals"
    },
    {
      number: 30,
      slug: "authority",
      name: "Authority",
      group: "coordination",
      question: "Who decides?",
      essence: "The asymmetric right to change state or enforce invariants.",
      why: "Authority resolves disagreement about which transition prevails.",
      absence: "Disagreements have no resolution mechanism other than force or drift.",
      domains: ["root access", "governance rights", "regulators", "management", "parental authority", "courts"],
      visual: "mandate"
    },
    {
      number: 31,
      slug: "reconciliation",
      name: "Reconciliation",
      group: "coordination",
      question: "How do divergent states converge?",
      essence: "Detecting divergence between states that should agree and resolving it under constraints.",
      why: "Reconciliation is where real-world coordination complexity concentrates.",
      absence: "Contradictions accumulate until different parts of the system inhabit incompatible realities.",
      domains: ["merge conflicts", "audits", "clearinghouses", "truth commissions", "conflict resolution", "standardization"],
      visual: "merge",
      composition: ["communication", "invariant", "authority"]
    },
    {
      number: 32,
      slug: "negotiation",
      name: "Negotiation",
      group: "coordination",
      question: "How do agents with competing interests reach agreement?",
      essence: "Agents under scarcity communicating to reach a mutually acceptable outcome.",
      why: "Negotiation is the civilized alternative to unilateral action.",
      absence: "Competing interests escalate into stalemate, coercion, or conflict.",
      domains: ["protocol handshakes", "markets", "labor contracts", "therapy", "treaties", "coalitions"],
      visual: "convergence",
      composition: ["communication", "scarcity", "authority"]
    }
  ]
};
